# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera1/aligned_depth_to_color/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.05
    far_clipping_plane_distance: 1.30
    shadow_threshold: 0.2
    padding_scale: 5.0
    padding_offset: 0.08
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
    ns: camera1

  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera2/aligned_depth_to_color/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.05
    far_clipping_plane_distance: 1.30
    shadow_threshold: 0.2
    padding_scale: 5.0
    padding_offset: 0.08
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
    ns: camera2

#  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
#    image_topic: /camera3/aligned_depth_to_color/image_raw
#    queue_size: 1
#    near_clipping_plane_distance: 0.05
#    far_clipping_plane_distance: 1.30
#    shadow_threshold: 0.2
#    padding_scale: 5.0
#    padding_offset: 0.08
#    max_update_rate: 1.0
#    filtered_cloud_topic: filtered_cloud
#    ns: camera3



#    The general parameters are:
#    sensor_plugin: The name of the plugin that we are using.
#    max_update_rate: The octomap representation will be updated at rate less than or equal to this value.

#    Parameters specific to the Depth Map updater are:
#    image_topic: This specifies the topic to listen on for a depth image.
#    queue_size: The number of images to queue up.
#    near_clipping_plane_distance: The minimum distance before lack of visibility.
#    far_clipping_plane_distance: The maximum distance before lack of visibility.
#    shadow_threshold: The minimum brightness of the shadow map below an entity for its dynamic shadow to be visible
#    padding_scale: Should always be >= 1.0. Scale up collision shapes in the scene before excluding them from the octomap.
#    padding_offset: Absolute padding (in m) around scaled collision shapes when excluding them from the octomap.
#    filtered_cloud_topic: The topic on which the filtered cloud will be published (mainly for debugging).
#    The filtering cloud is the resultant cloud after self-filtering has been performed. ns: An optional namespace
#    for the advertised topics. Required for multiple sensors of the same type.